# config/siope_layout.py
COL_TIPO = 0
COL_INSTITUICAO = 1
COL_PLANILHA = 2
COL_CODIGO = 3
COL_DESCRICAO = 4

# Receita Total (no seu CSV: 10 colunas)
COL_PREV_ATUAL = 5
COL_REALIZADA = 6
COL_DED_FUNDEB = 7
COL_OUTRAS_DED = 8
COL_INTRA = 9

# Despesa (ex.: 2384 no seu caso: 9 colunas)
COL_DOT_ATUAL = 5
COL_EMPENHADO = 6
COL_LIQUIDADO = 7
COL_PAGO = 8